apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    app.kubernetes.io/created-by: bpfman-catalog-cli
    app.kubernetes.io/name: bpfman-operator
    app.kubernetes.io/version: latest
    bpfman-catalog-cli: ab4b7126
    bpfman-catalog-cli/digest: ab4b7126
  name: bpfman-subscription-sha-ab4b7126
  namespace: bpfman-sha-ab4b7126
spec:
  channel: preview
  installPlanApproval: Automatic
  name: bpfman-operator
  source: bpfman-catalogsource-sha-ab4b7126
  sourceNamespace: openshift-marketplace
