apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/created-by: bpfman-catalog-cli
    app.kubernetes.io/name: bpfman-operator
    app.kubernetes.io/version: latest
    bpfman-catalog-cli: ab4b7126
    bpfman-catalog-cli/digest: ab4b7126
    openshift.io/cluster-monitoring: "true"
  name: bpfman-sha-ab4b7126
