apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  labels:
    app.kubernetes.io/created-by: bpfman-catalog-cli
    app.kubernetes.io/name: bpfman-operator
    app.kubernetes.io/version: latest
    bpfman-catalog-cli: ab4b7126
    bpfman-catalog-cli/digest: ab4b7126
  name: bpfman-idms-sha-ab4b7126
spec:
  imageDigestMirrors:
  - mirrors:
    - registry.stage.redhat.io/openshift4
    - registry-proxy.engineering.redhat.com/rh-osbs/openshift4
    source: registry.redhat.io/openshift4
